import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Helper to add a clean, professional header to the PDF document.
 * Includes the "Axiom Software Group" branding.
 * @param {jsPDF} doc - jsPDF instance
 * @param {string} title - Document title
 */
const addHeader = (doc, title) => {
  // Brand Header Background
  doc.setFillColor(79, 70, 229); // Indigo #4f46e5
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 35, 'F');

  // Brand Name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('AXIOM SOFTWARE GROUP', 15, 15);

  // Subtitle / Curriculum branding
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(199, 210, 254); // Light indigo
  doc.text('Curriculum Design & Planning Suite', 15, 22);

  // Document Title (Right-aligned)
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.text(title.toUpperCase(), pageWidth - 15, 18, { align: 'right' });

  // Thin line below header area (spacing helper)
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(0.5);
  doc.line(0, 35, pageWidth, 35);
};

/**
 * Helper to add a professional footer to the PDF document.
 * @param {jsPDF} doc - jsPDF instance
 * @param {number} pageNum - Current page number
 */
const addFooter = (doc, pageNum) => {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // Footer Line
  doc.setDrawColor(226, 232, 240); // Slate #e2e8f0
  doc.setLineWidth(0.5);
  doc.line(15, pageHeight - 20, pageWidth - 15, pageHeight - 20);

  // Footer Text
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(148, 163, 184); // Slate #94a3b8
  doc.text('Confidential - Generated by Axiom Education App', 15, pageHeight - 12);
  doc.text(`Page ${pageNum}`, pageWidth - 15, pageHeight - 12, { align: 'right' });
};

/**
 * Formats data value (string or array) into readable text format.
 * @param {any} value - Value to format
 * @returns {string} Formatted string
 */
const formatValue = (value) => {
  if (!value) return 'N/A';
  if (Array.isArray(value)) {
    return value.map(item => `• ${item}`).join('\n');
  }
  if (typeof value === 'object') {
    return Object.entries(value)
      .map(([key, val]) => `${key}: ${val}`)
      .join('\n');
  }
  return String(value);
};

/**
 * Generates a styled Lesson Plan PDF.
 * @param {object} lessonPlan - Lesson plan data object
 */
export const generateLessonPlanPDF = (lessonPlan) => {
  if (!lessonPlan) return;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  addHeader(doc, 'Lesson Plan');

  let currentY = 48;
  const marginX = 15;
  const pageWidth = doc.internal.pageSize.getWidth();
  const maxTextWidth = pageWidth - (2 * marginX);

  const sections = [
    { title: 'Objectives', key: 'objectives', icon: '🎯' },
    { title: 'Materials Needed', key: 'materials', icon: '📚' },
    { title: 'Lesson Introduction', key: 'introduction', icon: '🏁' },
    { title: 'Learning Activities', key: 'activities', icon: '📝' },
    { title: 'Evaluation & Assessment', key: 'evaluation', icon: '📊' },
  ];

  sections.forEach((section) => {
    // 1. Draw Section Header Background
    doc.setFillColor(248, 250, 252); // Slate #f8fafc
    doc.rect(marginX, currentY - 5, maxTextWidth, 8, 'F');
    doc.setDrawColor(226, 232, 240); // Slate #e2e8f0
    doc.line(marginX, currentY - 5, marginX, currentY + 3); // Left accent line

    // 2. Draw Section Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(79, 70, 229); // Indigo
    doc.text(`${section.icon} ${section.title}`, marginX + 3, currentY);

    currentY += 8;

    // 3. Draw Section Content
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);
    doc.setTextColor(51, 65, 85); // Slate #334155
    
    const textContent = formatValue(lessonPlan[section.key]);
    const splitText = doc.splitTextToSize(textContent, maxTextWidth - 6);
    
    // Check if we need a new page before drawing text
    const textHeight = splitText.length * 5;
    if (currentY + textHeight > doc.internal.pageSize.getHeight() - 25) {
      doc.addPage();
      addHeader(doc, 'Lesson Plan');
      currentY = 48;
    }

    doc.text(splitText, marginX + 3, currentY);
    currentY += textHeight + 12;
  });

  // Add footer to all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  doc.save(`Axiom-Lesson-Plan-${Date.now()}.pdf`);
};

/**
 * Generates a styled Record of Work PDF using autoTable.
 * @param {object|array} recordOfWork - Record of work data (array of entries or single object)
 */
export const generateRecordOfWorkPDF = (recordOfWork) => {
  if (!recordOfWork) return;

  const doc = new jsPDF({
    orientation: 'landscape', // Landscape is better for wide tabular records
    unit: 'mm',
    format: 'a4',
  });

  addHeader(doc, 'Record of Work');

  // Normalize record of work into an array of entries
  let entries = [];
  if (Array.isArray(recordOfWork)) {
    entries = recordOfWork;
  } else if (typeof recordOfWork === 'object') {
    // If it is an object containing arrays of same length
    const keys = Object.keys(recordOfWork);
    const firstKey = keys[0];
    if (firstKey && Array.isArray(recordOfWork[firstKey])) {
      const length = recordOfWork[firstKey].length;
      for (let i = 0; i < length; i++) {
        const entry = {};
        keys.forEach(k => {
          entry[k] = recordOfWork[k][i];
        });
        entries.push(entry);
      }
    } else {
      // Just put the object itself as a single entry
      entries = [recordOfWork];
    }
  }

  // Define columns
  const columns = [
    { header: 'Week', dataKey: 'week' },
    { header: 'Date', dataKey: 'date' },
    { header: 'Topic', dataKey: 'topic' },
    { header: 'Sub-Topic', dataKey: 'subTopic' }, // handle camelCase or lowercase
    { header: 'Remarks', dataKey: 'remarks' },
  ];

  // Map entries to row data, resolving field name variations
  const rows = entries.map((entry) => ({
    week: entry.week || entry.Week || 'N/A',
    date: entry.date || entry.Date || 'N/A',
    topic: entry.topic || entry.Topic || 'N/A',
    subTopic: entry.subTopic || entry['sub-topic'] || entry.subtopic || entry.SubTopic || 'N/A',
    remarks: entry.remarks || entry.Remarks || '—',
  }));

  // Render Table
  autoTable(doc, {
    startY: 45,
    columns: columns,
    body: rows,
    theme: 'striped',
    headStyles: {
      fillColor: [79, 70, 229], // Indigo #4f46e5
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
      halign: 'left',
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [51, 65, 85], // Slate #334155
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252], // Slate #f8fafc
    },
    margin: { horizontal: 15 },
    didDrawPage: (data) => {
      // Re-add header and footer on additional pages if table spans multiple pages
      if (data.pageNumber > 1) {
        addHeader(doc, 'Record of Work');
      }
    },
  });

  // Add footer to all pages
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    addFooter(doc, i);
  }

  doc.save(`Axiom-Record-of-Work-${Date.now()}.pdf`);
};
